server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include=*:
sentinel:
  flow:
    rule:
      "[{\"clusterConfig\":{\"acquireRefuseStrategy\":0,\"clientOfflineTime\":2000,\"fallbackToLocalWhenFail\":true,\"resourceTimeout\":2000,\"resourceTimeoutStrategy\":0,\"sampleCount\":10,\"strategy\":0,\"thresholdType\":0,\"windowIntervalMs\":1000},\"clusterMode\":false,\"controlBehavior\":0,\"count\":5,\"grade\":1,\"limitApp\":\"default\",\"maxQueueingTimeMs\":500,\"resource\":\"testC\",\"strategy\":0,\"warmUpPeriodSec\":10,\"paramFlowItemList\":[{\"paramIdx\":1,\"fieldName\":\"name\",\"burstCount\":1,\"maxQueueingTimeMs\":500,\"paramFlowItemList\":[],\"controlBehavior\":1,\"grade\":1,\"strategy\":0}]}]"
test:
  valueA:
    "[123]"
